# Pandas
Python advanced data analysis toolkit

Hauptwerkzeug zum Verarbeiten von Daten

In [1]:
import numpy as np
import pandas as pd
from IPython.core.pylabtools import figsize

## Serie
Ein Numpy Array mit extra Eigenschaften
- Name
- Benannter Index
- ...
Auf das unterliegen Numpy Array kann immer zugegriffen werden

In [8]:
e=pd.Series([8.6, 87.9, 0.23, 9]) # diese Zahlen alleine sagen viel aus

### Name

In [14]:
e.name = "Einwohnerzahlen (Millionen)"

In [15]:
e

CH     8.60
DE    87.90
LI     0.23
AT     9.00
Name: Einwohnerzahlen (Millionen), dtype: float64

### Index

In [16]:
e.index = ["CH", "DE", "LI", "AT"]

In [17]:
e

CH     8.60
DE    87.90
LI     0.23
AT     9.00
Name: Einwohnerzahlen (Millionen), dtype: float64

In [18]:
e["DE"]

np.float64(87.9)

In [19]:
e["DE":"AT"]

DE    87.90
LI     0.23
AT     9.00
Name: Einwohnerzahlen (Millionen), dtype: float64

In [20]:
e.values # Das unterliegene numpy Array

array([ 8.6 , 87.9 ,  0.23,  9.  ])

#### Vektorisierung wie bei Arrays

In [21]:
e>5

CH     True
DE     True
LI    False
AT     True
Name: Einwohnerzahlen (Millionen), dtype: bool

In [22]:
e[e>5]

CH     8.6
DE    87.9
AT     9.0
Name: Einwohnerzahlen (Millionen), dtype: float64

In [23]:
e[e>e.mean()]

DE    87.9
Name: Einwohnerzahlen (Millionen), dtype: float64

## DataFrame
Effektiv eine Tabelle

Wird generell aus einer Datenquelle erzeugt

In [24]:
pd.DataFrame({"Spalte1": [1,2,3], "Spalte2": [1,2,3], "Spalte3": [1,2,3]})

   Spalte1  Spalte2  Spalte3
0        1        1        1
1        2        2        2
2        3        3        3

### read_csv
Daten werden aus einer CSV-Datei eingelesen

Wird per Paramameter konfiguriert#

Beispiele:
- delimiter
- thousands
- decimal
- parse_dates
- index_col
- ...
https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

In [94]:
data = pd.read_csv("data/PopulationData.csv", delimiter = ";", thousands = ",", decimal = ".")

In [95]:
data

,#,Country (or dependency),Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
0,1,China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
1,2,India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
2,3,United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
3,4,Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
4,5,Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...,...,...
230,231,Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
231,232,Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
232,233,Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
233,234,Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
234,235,Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [96]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   #                        235 non-null    int64
 1   Country (or dependency)  235 non-null    str
 2   Population(2020)         235 non-null    int64
 3   YearlyChange             235 non-null    str
 4   NetChange                235 non-null    int64
 5   Density(P/Km²)           235 non-null    int64
 6   Land Area(Km²)           235 non-null    int64
 7   Migrants(net)            201 non-null    float64
 8   Fert.Rate                235 non-null    str
 9   Med.Age                  235 non-null    str
 10  UrbanPop %               235 non-null    str
 11  WorldShare               235 non-null    str
dtypes: float64(1), int64(5), str(6)
memory usage: 22.2 KB

#### Probleme mit dem Datenset
DataFrame:
- Schlechte Spaltennamen
- Doppelter Index

Daten selbst:
- Prozentzeichen
- N.A.
- NaN
- Datentypen

##### Index setzen
set_index("Spaltenname) ODER index_col direkt bei read_csv

__WICHTIG__: Jeder Befehl erzeugt immer nur eine Kopie des Datensets
Zwei Optionen:
- Bestehende Variable überschreiben
- inplace

In [97]:
# data = data.set_index("Country (or dependency)")

In [98]:
data.set_index("Country (or dependency)", inplace=True)

In [99]:
data

,#,Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,,
China,1,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,2,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,3,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,4,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,5,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...,...
Montserrat,231,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,232,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,233,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,234,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,235,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [100]:
data.index.name = "Country"

In [101]:
data

,#,Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country,,,,,,,,,,,
China,1,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,2,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,3,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,4,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,5,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...,...
Montserrat,231,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,232,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,233,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,234,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,235,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

##### Spalten anpassen
- entfernen mit drop
- umbenennen mit rename (rename benötigt ein Dictionary mit den colums = Parameter)

In [102]:
data.drop(columns=["#"], inplace=True)

In [103]:
data

,Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [104]:
data.rename(columns= {
    "Population(2020)": "Population",
    "Density(P/Km²)": "Density",
    "Land Area(Km²)": "LandArea",
    "Migrants(net)": "Migrants",
    "Fert.Rate": "FertRate",
    "Med.Age": "MedAge",
    "UrbanPop %": "UrbanPopPct",
    "WorldShare": "WorldSharePct"
}, inplace = True)

In [105]:
data

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

##### Daten speichern

In [106]:
data.to_csv("data/PopulationDataNearlyDone.csv")

##### Daten analysieren
Verschiedene Funktionen, um Erkenntisse aus den Daten zu ziehen

In [107]:
data.head(3) # Ersten 3 Datensätze (Zeilen)

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %

In [108]:
data.tail(3) # Untersten 3 DS

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

###### Sortieren
- sort_index()
- sort_values(["S1", "S2])
Alle Sortierungen können auch mit ascending =True/False angegeben werden

In [109]:
data.sort_index()

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
Afghanistan,38928346,2.33 %,886592,60,652860,-62920.0,4.6,18,25 %,0.50 %
Albania,2877797,-0.11 %,-3120,105,27400,-14000.0,1.6,36,63 %,0.04 %
Algeria,43851044,1.85 %,797990,18,2381740,-10000.0,3.1,29,73 %,0.56 %
American Samoa,55191,-0.22 %,-121,276,200,NaN,N.A.,N.A.,88 %,0.00 %
Andorra,77265,0.16 %,123,164,470,NaN,N.A.,N.A.,88 %,0.00 %
...,...,...,...,...,...,...,...,...,...,...
Wallis & Futuna,11239,-1.69 %,-193,80,140,NaN,N.A.,N.A.,0 %,0.00 %
Western Sahara,597339,2.55 %,14876,2,266000,5582.0,2.4,28,87 %,0.01 %
Yemen,29825964,2.28 %,664042,56,527970,-30000.0,3.8,20,38 %,0.38 %
Zambia,18383955,2.93 %,522925,25,743390,-8000.0,4.7,18,45 %,0.24 %
Zimbabwe,14862924,1.48 %,217456,38,386850,-116858.0,3.6,19,38 %,0.19 %

In [110]:
data.sort_index(ascending = False)

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
Zimbabwe,14862924,1.48 %,217456,38,386850,-116858.0,3.6,19,38 %,0.19 %
Zambia,18383955,2.93 %,522925,25,743390,-8000.0,4.7,18,45 %,0.24 %
Yemen,29825964,2.28 %,664042,56,527970,-30000.0,3.8,20,38 %,0.38 %
Western Sahara,597339,2.55 %,14876,2,266000,5582.0,2.4,28,87 %,0.01 %
Wallis & Futuna,11239,-1.69 %,-193,80,140,NaN,N.A.,N.A.,0 %,0.00 %
...,...,...,...,...,...,...,...,...,...,...
Andorra,77265,0.16 %,123,164,470,NaN,N.A.,N.A.,88 %,0.00 %
American Samoa,55191,-0.22 %,-121,276,200,NaN,N.A.,N.A.,88 %,0.00 %
Algeria,43851044,1.85 %,797990,18,2381740,-10000.0,3.1,29,73 %,0.56 %
Albania,2877797,-0.11 %,-3120,105,27400,-14000.0,1.6,36,63 %,0.04 %
Afghanistan,38928346,2.33 %,886592,60,652860,-62920.0,4.6,18,25 %,0.50 %

In [111]:
data.sort_values("LandArea", ascending = False)

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
Russia,145934462,0.04 %,62206,9,16376870,182456.0,1.8,40,74 %,1.87 %
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Canada,37742154,0.89 %,331107,4,9093510,242032.0,1.5,41,81 %,0.48 %
Brazil,212559417,0.72 %,1509890,25,8358140,21200.0,1.7,33,88 %,2.73 %
...,...,...,...,...,...,...,...,...,...,...
Nauru,10824,0.63 %,68,541,20,NaN,N.A.,N.A.,N.A.,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Gibraltar,33691,-0.03 %,-10,3369,10,NaN,N.A.,N.A.,N.A.,0.00 %
Monaco,39242,0.71 %,278,26337,1,NaN,N.A.,N.A.,N.A.,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [112]:
data.sort_values(["LandArea", "Population"], ascending = False)

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
Russia,145934462,0.04 %,62206,9,16376870,182456.0,1.8,40,74 %,1.87 %
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Canada,37742154,0.89 %,331107,4,9093510,242032.0,1.5,41,81 %,0.48 %
Brazil,212559417,0.72 %,1509890,25,8358140,21200.0,1.7,33,88 %,2.73 %
...,...,...,...,...,...,...,...,...,...,...
Nauru,10824,0.63 %,68,541,20,NaN,N.A.,N.A.,N.A.,0.00 %
Gibraltar,33691,-0.03 %,-10,3369,10,NaN,N.A.,N.A.,N.A.,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Monaco,39242,0.71 %,278,26337,1,NaN,N.A.,N.A.,N.A.,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [113]:
data.sort_values(["LandArea", "Population"], ascending = [False, True])

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
Russia,145934462,0.04 %,62206,9,16376870,182456.0,1.8,40,74 %,1.87 %
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Canada,37742154,0.89 %,331107,4,9093510,242032.0,1.5,41,81 %,0.48 %
Brazil,212559417,0.72 %,1509890,25,8358140,21200.0,1.7,33,88 %,2.73 %
...,...,...,...,...,...,...,...,...,...,...
Nauru,10824,0.63 %,68,541,20,NaN,N.A.,N.A.,N.A.,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Gibraltar,33691,-0.03 %,-10,3369,10,NaN,N.A.,N.A.,N.A.,0.00 %
Monaco,39242,0.71 %,278,26337,1,NaN,N.A.,N.A.,N.A.,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

##### Auf Daten zugreifen
Drei Möglichkeiten
- Index: Zugriff auf Zeilen/Spalten Kombinationen
- loc: Mehrere Spalten
- iloc: Wie loc, aber nur mit Zahlen

In [114]:
data["Population"] # Eine Spalte oder Zeile eines Dictionarys ist eine Serie

Country
China               1439323776
India               1380004385
United States        331002651
Indonesia            273523615
Pakistan             220892340
                       ...
Montserrat                4992
Falkland Islands          3480
Niue                      1626
Tokelau                   1357
Vatican State              801
Name: Population, Length: 235, dtype: int64

In [115]:
data["China":"China"]

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %

In [116]:
data["China":"Russia"] # meherere Zeilen

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
Brazil,212559417,0.72 %,1509890,25,8358140,21200.0,1.7,33,88 %,2.73 %
Nigeria,206139589,2.58 %,5175990,226,910770,-60000.0,5.4,18,52 %,2.64 %
Bangladesh,164689383,1.01 %,1643222,1265,130170,-369501.0,2.1,28,39 %,2.11 %
Russia,145934462,0.04 %,62206,9,16376870,182456.0,1.8,40,74 %,1.87 %

In [117]:
data["Density"]["India"] #Einzelne Werte

np.int64(464)

In [118]:
data["Population"]["China":"Russia"] #Mehrere Zeilen einer Spalte

Country
China            1439323776
India            1380004385
United States     331002651
Indonesia         273523615
Pakistan          220892340
Brazil            212559417
Nigeria           206139589
Bangladesh        164689383
Russia            145934462
Name: Population, dtype: int64

In [119]:
data.loc["China":"Russia", "Population":"Density"] #Mehrere Zeilen einer Spalte

               Population YearlyChange  NetChange  Density
Country
China          1439323776       0.39 %    5540090      153
India          1380004385       0.99 %   13586631      464
United States   331002651       0.59 %    1937734       36
Indonesia       273523615       1.07 %    2898047      151
Pakistan        220892340       2.00 %    4327022      287
Brazil          212559417       0.72 %    1509890       25
Nigeria         206139589       2.58 %    5175990      226
Bangladesh      164689383       1.01 %    1643222     1265
Russia          145934462       0.04 %      62206        9

In [120]:
data.loc["China":"Russia", ("Population","Density")] # Einzelne Spalten selektieren

               Population  Density
Country
China          1439323776      153
India          1380004385      464
United States   331002651       36
Indonesia       273523615      151
Pakistan        220892340      287
Brazil          212559417       25
Nigeria         206139589      226
Bangladesh      164689383     1265
Russia          145934462        9

In [121]:
data.loc[("China","Russia"), :] # Einzelne Zeilen selektieren

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
Russia,145934462,0.04 %,62206,9,16376870,182456.0,1.8,40,74 %,1.87 %

In [122]:
data.iloc[10:20, 0:3]

             Population YearlyChange  NetChange
Country
Japan         126476461      -0.30 %    -383840
Ethiopia      114963588       2.57 %    2884858
Philippines   109581078       1.35 %    1464463
Egypt         102334404       1.94 %    1946331
Vietnam        97338579       0.91 %     876473
DR Congo       89561403       3.19 %    2770836
Turkey         84339067       1.09 %     909452
Iran           83992949       1.30 %    1079043
Germany        83783942       0.32 %     266897
Thailand       69799978       0.25 %     174396

#### Daten filtern
Funktioniert wie bei Numpy (Vektorisierung mit Boolschen Operatoren und Masken)

In [123]:
data["Population"] > 50_000_000

Country
China                True
India                True
United States        True
Indonesia            True
Pakistan             True
                    ...
Montserrat          False
Falkland Islands    False
Niue                False
Tokelau             False
Vatican State       False
Name: Population, Length: 235, dtype: bool

In [124]:
data[data["Population"] > 50_000_000]

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
Brazil,212559417,0.72 %,1509890,25,8358140,21200.0,1.7,33,88 %,2.73 %
Nigeria,206139589,2.58 %,5175990,226,910770,-60000.0,5.4,18,52 %,2.64 %
Bangladesh,164689383,1.01 %,1643222,1265,130170,-369501.0,2.1,28,39 %,2.11 %
Russia,145934462,0.04 %,62206,9,16376870,182456.0,1.8,40,74 %,1.87 %
Mexico,128932753,1.06 %,1357224,66,1943950,-60000.0,2.1,29,84 %,1.65 %
Japan,126476461,-0.30 %,-383840,347,364555,71560.0,1.4,48,92 %,1.62 %
Ethiopia,114963588,2.57 %,2884858,115,1000000,30000.0,4.3,19,21 %,1.47 %
Philippines,109581078,1.35 %,1464463,368,298170,-67152.0,2.6,26,47 %,1.41 %
Egypt,102334404,1.94 %,1946331,103,995450,-38033.0,3.3,25,43 %,1.31 %
Vietnam,97338579,0.91 %,876473,314,310070,-80000.0,2.1,32,38 %,1.25 %
DR Congo,89561403,3.19 %,2770836,40,2267050,23861.0,6.0,17,46 %,1.15 %
Turkey,84339067,1.09 %,909452,110,769630,283922.0,2.1,32,76 %,1.08 %
Iran,83992949,1.30 %,1079043,52,1628550,-55000.0,2.2,32,76 %,1.08 %
Germany,83783942,0.32 %,266897,240,348560,543822.0,1.6,46,76 %,1.07 %
Thailand,69799978,0.25 %,174396,137,510890,19444.0,1.5,40,51 %,0.90 %
United Kingdom,67886011,0.53 %,355839,281,241930,260650.0,1.8,40,83 %,0.87 %
France,65273511,0.22 %,143783,119,547557,36527.0,1.9,42,82 %,0.84 %
Italy,60461826,-0.15 %,-88249,206,294140,148943.0,1.3,47,69 %,0.78 %
Tanzania,59734218,2.98 %,1728755,67,885800,-40076.0,4.9,18,37 %,0.77 %
South Africa,59308690,1.28 %,750420,49,1213090,145405.0,2.4,28,67 %,0.76 %
Myanmar,54409800,0.67 %,364380,83,653290,-163313.0,2.2,29,31 %,0.70 %
Kenya,53771296,2.28 %,1197323,94,569140,-10000.0,3.5,20,28 %,0.69 %
South Korea,51269185,0.09 %,43877,527,97230,11731.0,1.1,44,82 %,0.66 %
Colombia,50882891,1.08 %,543448,46,1109500,204796.0,1.8,31,80 %,0.65 %

#### Gruppierung
groupby(Spalte)

In [125]:
g = data.groupby("MedAge")

In [126]:
g

In [127]:
g.get_group("20")

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
Kenya,53771296,2.28 %,1197323,94,569140,-10000.0,3.5,20,28 %,0.69 %
Sudan,43849260,2.42 %,1036022,25,1765048,-50000.0,4.4,20,35 %,0.56 %
Yemen,29825964,2.28 %,664042,56,527970,-30000.0,3.8,20,38 %,0.38 %
Madagascar,27691018,2.68 %,721711,48,581795,-1500.0,4.1,20,39 %,0.36 %
Rwanda,12952218,2.58 %,325268,525,24670,-9000.0,4.1,20,18 %,0.17 %
Mauritania,4649658,2.74 %,123962,5,1030700,5000.0,4.6,20,57 %,0.06 %
Comoros,869601,2.20 %,18715,467,1861,-2000.0,4.2,20,29 %,0.01 %
Solomon Islands,686884,2.55 %,17061,25,27990,-1600.0,4.4,20,23 %,0.01 %
Mayotte,272815,2.50 %,6665,728,375,0.0,3.7,20,46 %,0.00 %

In [128]:
g["Population"].count() # wievele Einträge gibt es pro Gruppe

MedAge
15       1
16       1
17       6
18      10
19      14
20       9
21       5
22       7
23       4
24       6
25       4
26       7
27       4
28      12
29       5
30       8
31       6
32      11
33       5
34       6
35       3
36       4
37       4
38       7
39       3
40       7
41       5
42      10
43      11
44       5
45       5
46       3
47       2
48       1
N.A.    34
Name: Population, dtype: int64

In [129]:
g["Population"].sum()

MedAge
15        24206644
16        20250833
17       212378552
18       414853998
19       255376557
20       174568714
21        48109661
22        53805608
23       241153091
24        43279705
25       132167522
26       175755009
27         8354666
28      1678548499
29       234651521
30       391572405
31       110868020
32       361345291
33       239473496
34        22359558
35        47858260
36         8646327
37         7090941
38      1813609460
39         3360775
40       299404368
41        97141589
42       171723679
43        83944285
44        60521627
45        66001431
46       104403705
47        60837091
48       126476461
N.A.       1133281
Name: Population, dtype: int64

In [130]:
g["Population"].mean().astype(np.int32).sort_values()

MedAge
N.A.        33331
39        1120258
37        1772735
27        2088666
36        2161581
34        3726593
24        7213284
43        7631298
22        7686515
21        9621932
44       12104325
45       13200286
35       15952753
42       17172367
19       18241182
31       18478003
20       19396523
41       19428317
16       20250833
15       24206644
26       25107858
47       30418545
32       32849571
25       33041880
46       34801235
17       35396425
18       41485399
40       42772052
29       46930304
33       47894699
30       48946550
23       60288272
48      126476461
28      139879041
38      259087065
Name: Population, dtype: int32